site_name: 通识课课程评价
site_url: https://thu-general-course-evaluation.github.io/THU-General-Course-Eevaluation/
repo_url: https://github.com/THU-General-Course-Evaluation/THU-General-Course-Eevaluation
repo_name: THU-General-Course-Eevaluation
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true
nav:
  - 首页: index.md
  - 课程评价: courses/index.md
  - 贡献指南: contribute.md
